# Generated by Django 2.2.4 on 2021-04-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('is_night', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'models.days',
                'verbose_name_plural': 'models.days',
                'db_table': 'days',
                'ordering': ['-room', '-id'],
                'default_related_name': 'days_set',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'models.room',
                'verbose_name_plural': 'models.room',
                'db_table': 'room',
                'ordering': ['-id'],
                'default_related_name': 'room_set',
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_id', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('wolf', '人狼'), ('villager', '村人'), ('teller', '占い師')], max_length=255)),
                ('is_master', models.BooleanField(default=False)),
                ('is_dead', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_member_set', to='line.Room')),
            ],
            options={
                'verbose_name': 'models.room_member',
                'verbose_name_plural': 'models.room_member',
                'db_table': 'room_member',
                'ordering': ['-room', '-id'],
                'default_related_name': 'room_member_set',
            },
        ),
        migrations.CreateModel(
            name='MemberAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_action_set', to='line.Days')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='line.RoomMember')),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_member', to='line.RoomMember')),
            ],
            options={
                'verbose_name': 'models.member_action',
                'verbose_name_plural': 'models.member_action',
                'db_table': 'member_action',
                'ordering': ['-member', '-id'],
                'default_related_name': 'member_action_set',
            },
        ),
        migrations.AddField(
            model_name='days',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_set', to='line.Room'),
        ),
    ]
