# Generated by Django 2.2.4 on 2021-05-01 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'models.rich_menu',
                'verbose_name_plural': 'models.rich_menu',
                'db_table': 'rich_menu',
                'ordering': ['-id'],
                'default_related_name': 'menu_id_set',
            },
        ),
        migrations.CreateModel(
            name='WordWolfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vil_img', models.CharField(max_length=255)),
                ('wolf_img', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'models.word_wolf_item',
                'verbose_name_plural': 'models.word_wolf_item',
                'db_table': 'word_wolf_item',
                'ordering': ['-id'],
                'default_related_name': 'word_wolf_item_set',
            },
        ),
        migrations.AddField(
            model_name='days',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='days',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memberaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommember',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('playing', 'playing'), ('ended', 'ended')], default='init', max_length=255),
        ),
        migrations.AddField(
            model_name='roommember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_set', to='line.WordWolfItem'),
        ),
    ]
