# Generated by Django 2.2.4 on 2021-05-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_auto_20210501_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richmenu',
            options={'default_related_name': 'rich_menu_set', 'ordering': ['-id'], 'verbose_name': 'models.rich_menu', 'verbose_name_plural': 'models.rich_menu'},
        ),
        migrations.AlterField(
            model_name='memberaction',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_action_set', to='line.Days'),
        ),
    ]
